export const DiagnosisTheme = {
  canvas: '#F6F2EA',
  panel: '#FFFCF8',
  panelAlt: '#F7F3EC',
  ink: '#243229',
  inkMuted: '#667268',
  line: '#D9E0D4',
  heroBg: '#FBF8F1',
  heroAccent: '#D9E7D7',
  userBubble: '#2F5A43',
  userBubbleText: '#FFFFFF',
  assistantBubble: '#FFFFFF',
  assistantBubbleBorder: '#E2E7DE',
  choiceBg: '#FFFFFF',
  choiceBorder: '#DCE4DA',
  choiceActiveBg: '#EEF4EE',
  choiceActiveBorder: '#89A78E',
  infoBg: '#F3F7F1',
  infoBorder: '#D6E2D4',
  successBg: '#EEF7EF',
  successBorder: '#B8D6BF',
  warningBg: '#FFF6E8',
  warningBorder: '#E7C98A',
} as const;
