"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteAccountUrl = exports.reviewFeedbackTimeoutMs = exports.reviewFeedbackUrl = exports.diagnosisExplainTimeoutMs = exports.diagnosisRouterTimeoutMs = exports.learningHistoryListReviewTasksUrl = exports.learningHistoryImportLocalSnapshotUrl = exports.learningHistoryGetLearningAttemptResultsUrl = exports.learningHistoryListLearningAttemptsUrl = exports.learningHistorySaveFeaturedExamStateUrl = exports.learningHistoryGetLearnerSummaryUrl = exports.learningHistoryRecordAttemptUrl = exports.expoPublicGoogleWebClientId = exports.expoPublicGoogleAndroidClientId = exports.expoPublicGoogleIosClientId = exports.expoPublicFirebaseStorageBucket = exports.expoPublicFirebaseMessagingSenderId = exports.expoPublicFirebaseAppId = exports.expoPublicFirebaseProjectId = exports.expoPublicFirebaseAuthDomain = exports.expoPublicFirebaseApiKey = exports.diagnosisExplainUrl = exports.diagnosisRouterUrl = void 0;
exports.diagnosisRouterUrl = (process.env.EXPO_PUBLIC_DIAGNOSIS_ROUTER_URL ?? '').trim();
exports.diagnosisExplainUrl = (process.env.EXPO_PUBLIC_DIAGNOSIS_EXPLAIN_URL ?? '').trim();
exports.expoPublicFirebaseApiKey = (process.env.EXPO_PUBLIC_FIREBASE_API_KEY ?? '').trim();
exports.expoPublicFirebaseAuthDomain = (process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN ?? '').trim();
exports.expoPublicFirebaseProjectId = (process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID ?? '').trim();
exports.expoPublicFirebaseAppId = (process.env.EXPO_PUBLIC_FIREBASE_APP_ID ?? '').trim();
exports.expoPublicFirebaseMessagingSenderId = (process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '').trim();
exports.expoPublicFirebaseStorageBucket = (process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET ?? '').trim();
exports.expoPublicGoogleIosClientId = (process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID ?? '').trim();
exports.expoPublicGoogleAndroidClientId = (process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ?? '').trim();
exports.expoPublicGoogleWebClientId = (process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ?? '').trim();
exports.learningHistoryRecordAttemptUrl = (process.env.EXPO_PUBLIC_RECORD_LEARNING_ATTEMPT_URL ?? '').trim();
exports.learningHistoryGetLearnerSummaryUrl = (process.env.EXPO_PUBLIC_GET_LEARNER_SUMMARY_URL ?? '').trim();
exports.learningHistorySaveFeaturedExamStateUrl = (process.env.EXPO_PUBLIC_SAVE_FEATURED_EXAM_STATE_URL ?? '').trim();
exports.learningHistoryListLearningAttemptsUrl = (process.env.EXPO_PUBLIC_LIST_LEARNING_ATTEMPTS_URL ?? '').trim();
exports.learningHistoryGetLearningAttemptResultsUrl = (process.env.EXPO_PUBLIC_GET_LEARNING_ATTEMPT_RESULTS_URL ?? '').trim();
exports.learningHistoryImportLocalSnapshotUrl = (process.env.EXPO_PUBLIC_IMPORT_LOCAL_LEARNING_HISTORY_URL ?? '').trim();
exports.learningHistoryListReviewTasksUrl = (process.env.EXPO_PUBLIC_LIST_REVIEW_TASKS_URL ?? '').trim();
exports.diagnosisRouterTimeoutMs = 8000;
exports.diagnosisExplainTimeoutMs = 12000;
exports.reviewFeedbackUrl = (process.env.EXPO_PUBLIC_REVIEW_FEEDBACK_URL ?? '').trim();
exports.reviewFeedbackTimeoutMs = 10000;
exports.deleteAccountUrl = (process.env.EXPO_PUBLIC_DELETE_ACCOUNT_URL ?? '').trim();
